version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
      - "marvel"
    commit-message:
      prefix: "chore(deps-gha)"
    groups:
      github-actions-weekly:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
